server:
  port: 9091
spring:
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: spring:session
  main:
    banner-mode: log
  application:
    name: service_web
