#Infos pour logging
logging:
  level:
    org.springframework: WARN
    com.netflix: WARN
    org.apache.catalina: WARN
    fr.ocr.reference_srv: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: ./logs/service_batchmail.log

#Email
spring:
  application:
    name: service_batchmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: laurent.cordier3004@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          starttls:
            enable: true
