server:
  port: 9092
#Email
spring:
  main:
    banner-mode: off
  application:
    name: service_batchmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: laurent.cordier3004@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          starttls:
            enable: true


